<#
.SYNOPSIS
    Local and CI build entry point.
.EXAMPLE
    ./build.ps1                # analyze + test
.EXAMPLE
    ./build.ps1 -Task Package  # copy the module to ./out ready for Publish-Module
#>
[CmdletBinding()]
param(
    [ValidateSet('Analyze', 'Test', 'Package', 'Docs', 'All')]
    [string[]] $Task = @('Analyze', 'Test')
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$source = Join-Path $root 'src/ADHealthCheck'
if ($Task -contains 'All') { $Task = @('Analyze', 'Test', 'Docs', 'Package') }

if ($Task -contains 'Analyze') {
    Write-Host '==> PSScriptAnalyzer' -ForegroundColor Cyan
    $findings = Invoke-ScriptAnalyzer -Path $source -Recurse -Settings (Join-Path $root 'PSScriptAnalyzerSettings.psd1')
    if ($findings) {
        $findings | Format-Table -AutoSize RuleName, Severity, ScriptName, Line, Message | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $(@($findings).Count) finding(s)."
    }
}

if ($Task -contains 'Test') {
    Write-Host '==> Pester' -ForegroundColor Cyan
    $config = New-PesterConfiguration
    $config.Run.Path = Join-Path $root 'tests'
    $config.Run.Exit = $false
    $config.Run.Throw = $true
    $config.Output.Verbosity = 'Detailed'
    $config.TestResult.Enabled = $true
    $config.TestResult.OutputPath = Join-Path $root 'out/testResults.xml'
    $config.CodeCoverage.Enabled = $true
    $config.CodeCoverage.Path = @((Join-Path $source 'Public'), (Join-Path $source 'Private'), (Join-Path $source 'Checks'))
    $config.CodeCoverage.OutputPath = Join-Path $root 'out/coverage.xml'
    $null = New-Item -Path (Join-Path $root 'out') -ItemType Directory -Force
    Invoke-Pester -Configuration $config
}

if ($Task -contains 'Docs') {
    Write-Host '==> docs/rules.md' -ForegroundColor Cyan
    Import-Module (Join-Path $source 'ADHealthCheck.psd1') -Force
    $lines = @('# Rule reference', '', 'Generated by `./build.ps1 -Task Docs`. Do not edit by hand.', '')
    $lines += '| Id | Category | Severity | Title |'
    $lines += '|---|---|---|---|'
    $definitions = Get-ADHealthCheckDefinition
    foreach ($rule in $definitions) {
        $anchor = $rule.Id.ToLowerInvariant()
        $lines += "| [$($rule.Id)](#$anchor) | $($rule.Category) | $($rule.Severity) | $($rule.Title) |"
    }
    foreach ($rule in $definitions) {
        $lines += ''
        $lines += "## $($rule.Id)"
        $lines += ''
        $lines += "**$($rule.Title)** - $($rule.Category), $($rule.Severity) severity"
        $lines += ''
        $lines += $rule.Description
        $lines += ''
        $lines += "**Recommendation:** $($rule.Recommendation)"
        $lines += ''
        $lines += "**Data used:** $($rule.Requires -join ', ')"
        $lines += ''
        $lines += ($rule.References | ForEach-Object { "- <$_>" })
    }
    $lines | Set-Content -Path (Join-Path $root 'docs/rules.md') -Encoding UTF8
}

if ($Task -contains 'Package') {
    Write-Host '==> Package' -ForegroundColor Cyan
    $version = (Import-PowerShellDataFile -Path (Join-Path $source 'ADHealthCheck.psd1')).ModuleVersion
    $target = Join-Path $root "out/ADHealthCheck/$version"
    if (Test-Path $target) { Remove-Item -Path $target -Recurse -Force }
    $null = New-Item -Path $target -ItemType Directory -Force
    Copy-Item -Path (Join-Path $source '*') -Destination $target -Recurse
    Write-Host "Module staged at $target"
}
